---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx # workload storage class
provisioner: nfs.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
mountOptions:
  - "vers=4.1"
  - "noresvport"
